- src/main/java/net/bramp/ffmpeg/builder/FFmpegBuilder.java
- src/test/java/net/bramp/ffmpeg/FFmpegBuilderTest.java
In order to support the input format parameters, a format attribute have been added to the FFmpegBuilder class and handle in the build method.
The parameter is mandatory for some operation like concatenation without re-encode (https://www.ffmpeg.org/ffmpeg-formats.html#concat). With this extra parameter, we can generate a command line like this : /usr/local/bin/ffmpeg -f concat -i /path/to/file.txt -vcodec copy -acodec copy /path/to/file.mp4
> feat(FFmpegBuilder): support -f for input

- src/main/java/net/bramp/ffmpeg/builder/FFmpegOutputBuilder.java
- src/test/java/net/bramp/ffmpeg/FFmpegBuilderTest.java
In order to add the possibility to use Bitstream filter for audio and video, some attribute have been added to the OutputBuilder so the parameters are integrated in the command line. This modification allow in my project (inked in this PR) to use the 'aac_adtstoasc' (https://www.ffmpeg.org/ffmpeg-bitstream-filters.html#aac_005fadtstoasc) which allow to merge a AAC and MP4 video together without re-encoding. This format t is the only one usable in web environnement without major re-enconding.
The support of this bitstream filters are quiet simple in this PR, but it can be complexified to support parameters in future release.
@bramp Do you think it could be integrated in the future 0.5 if accepted ?
Linked to https://github.com/davinkevin/Podcast-Server/issues/68
> feat(FFmpegBuilder): support -bsf:v and -bsf:a for bitstream filters

- src/main/java/net/bramp/ffmpeg/builder/FFmpegOutputBuilder.java
- src/test/java/net/bramp/ffmpeg/FFmpegBuilderTest.java
- src/test/java/net/bramp/ffmpeg/FFmpegExecutorTest.java
I added a simple implementation for adding metadata to the output video.
I realised it using an ArrayList, storing each "-metadata" value as a String. Thought about using a HashMap, but I didn't see a real reason for that.
> Implement adding metadata to output video.

- src/main/java/net/bramp/ffmpeg/FFmpeg.java
- src/main/java/net/bramp/ffmpeg/builder/FFmpegOutputBuilder.java
- src/main/java/net/bramp/ffmpeg/gson/NamedBitsetAdapter.java
- src/main/java/net/bramp/ffmpeg/modelmapper/Mapper.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1118 Utility classes should not have public constructors
squid:UselessParenthesesCheck Useless parentheses around expressions should be removed to prevent any misunderstanding
squid:S1185 Overriding methods should do more than simply call the same method in the super class
squid:HiddenFieldCheck Local variables should not shadow class fields
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1118
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
https://dev.eclipse.org/sonar/rules/show/squid:S1185
https://dev.eclipse.org/sonar/rules/show/squid:HiddenFieldCheck
Please let me know if you have any questions.
Zeeshan Asghar
> General Code Improvement 2

- src/main/java/net/bramp/ffmpeg/builder/FFmpegBuilder.java
- src/test/java/net/bramp/ffmpeg/builder/FFmpegBuilderTest.java
I'v created an enum with all the possible value and define a default value in the builder to the previous hard coded level (ERROR). The user can set verbosity with method `setVerbosity(Verbosity v)`. 
This will help us to develop the issue #21 because we need a certain level of information to display / send the progresion of a ffmpeg operation
> feat(builder): set log level programmatically

- README.md
Small section in documentation to resolve #30.
> Document basic FFmpegProbeResult usage

- src/test/java/net/bramp/ffmpeg/builder/FFmpegOutputBuilderTestCheckInvalidStream.java
- src/test/java/net/bramp/ffmpeg/builder/FFmpegOutputBuilderTestCheckValidStream.java
Use 2 distinct test classes for valid and invalid URIs.
> Refactor FFmpegOutputBuilderTestCheckValidStream

- pom.xml
> Maven - Add reporting section

- pom.xml
Fix warning message "Duplicating managed version 2.7 for cobertura-maven-plugin" in Eclipse
> Duplicating managed version for Cobertura

- .travis.yml
- README.md
- src/test/java/net/bramp/ffmpeg/ReadmeTest.java
Ensure Maven tests are OK for any language/file encoding.
> Maven test - Fix locale issue

- src/main/java/net/bramp/ffmpeg/builder/AbstractFFmpegStreamBuilder.java
- src/main/java/net/bramp/ffmpeg/builder/FFmpegOutputBuilder.java
- src/main/java/net/bramp/ffmpeg/modelmapper/Mapper.java
This PR makes it possible to provide args for each separate input. The rationale behind this is that there are certain args that apply to an input, and must be set before that input. An exampe of this is `itsoffset`, which sets the input time for the offset.
> Allow setting args per input

- src/main/java/net/bramp/ffmpeg/FFmpegUtils.java
- src/test/java/net/bramp/ffmpeg/FFmpegUtilsTest.java
A new pull request to fix bitrate parsing. The same solution (return -1 for 'N/A') with added javadoc and unit test.
> Fix #86: return -1 if given bitrate is 'N/A'

- src/main/java/net/bramp/ffmpeg/builder/FFmpegBuilder.java
- src/test/java/net/bramp/ffmpeg/ExamplesTest.java
Just a quick pull request to fix the `-af` and `-vf` arguments. They were flipped.
> Fix the audio and video filter arguments

- src/main/java/net/bramp/ffmpeg/FFprobe.java
- src/main/java/net/bramp/ffmpeg/probe/FFmpegChapter.java
- src/main/java/net/bramp/ffmpeg/probe/FFmpegChapterTag.java
- src/main/java/net/bramp/ffmpeg/probe/FFmpegProbeResult.java
- src/test/java/net/bramp/ffmpeg/FFprobeTest.java
- src/test/java/net/bramp/ffmpeg/fixtures/Samples.java
- src/test/resources/net/bramp/ffmpeg/fixtures/book_with_chapters.m4b
This fix implements chapters support by FFProbe, issue #212
> Fix for issue #212

- src/main/java/net/bramp/ffmpeg/builder/FFmpegOutputBuilder.java
Changed `setVideoFilterComplex` to `setComplexVideoFilter`.
The method `setVideoFilterComplex` does not exists which misleads developer as he cannot find this method.
> Fix misleading error message.

- .travis.yml
- travis-install-ffmpeg.sh
The latest release name changed format. It was `64bit` but now it's `amd64`
This should either fix or make progress on the failing build. If the build stops failing, the coveralls report might start working.
> Fix the name of the FFMpeg package

- src/main/java/net/bramp/ffmpeg/info/Codec.java
- src/test/java/net/bramp/ffmpeg/info/FFmpegGetInfoTest.java
When I wanna use the code in `FFmpegGetInfoTest`, but I found that the inner Enum `Codec.Type` is unable to access in the outside. 
So just simpley public this Enum please~
> public the Enum Codec.Type

- src/main/java/net/bramp/ffmpeg/FFprobe.java
The `-user-agent` tag has been deprecated, the new tag is `-user_agent`.
This pr replaces the deprecated form with the current format.
Fix #209
> Fix #209 -user-agent tag is not supported

- src/main/java/net/bramp/ffmpeg/probe/FFmpegStream.java
I've added the required CodecTypes for `SUBTITLE` and `ATTACHMENT`.
Additionally, I've added the `DATA` CodecType.
@bramp: These are all CodecTypes according to [Documentation](https://ffmpeg.org/ffmpeg.html#toc-Description).
Therefore, I fink we could also remove the corresponding TODO comment.
Fix #264
Fix #259
> Fix #264: Add additional CodecTypes to FFmpegStream

- src/test/java/net/bramp/ffmpeg/info/FFmpegGetInfoTest.java
PR #256 added a static reference that cannot be resolved unless we run on a specific environment.
Additionally, the runFunc has not been mocked, resulting in an actual call to the FFmpeg executable.
I have applied the following modifications:
- Mock load the regular mocks for `ffmpeg -version` and `ffmpeg -codecs`.
- Break after each case (the old syntax would otherwise fall through and add to all consecutive lists)
- Add a dataCodecs list and another codecs list (the second one should always be empty unless FFmpeg adds another CodecType)
- Add assertions for the size of each collection and assert the existence of at least one element within it
> Fix broken test: Mock runFunc and add assertions to FFmpegGetInfoTest

- src/main/java/net/bramp/ffmpeg/builder/AbstractFFmpegStreamBuilder.java
This adds an additional option `setSubtitleCodec` to specify the subtitle codec
Fix #266
> Fix #266: Add option to specify subtitle codec

- src/main/java/net/bramp/ffmpeg/FFmpegExecutor.java
The class ```TwoPassFFmpegJob``` had a method in it for including a ```ProgressListener```, but ```FFmpegExecutor``` did not have a method that would employ it. I simply added the method to the executor, tested it and it works fine.
I am curious, however ... ```ffmpeg``` has a command-line switch for two pass encoding, but this library seems to accomplish this manually ... why not just use the option that is built into ```ffmpeg```?
> Added method for using two pass with progress to class FFmpegExecutor

- pom.xml
- src/main/java/net/bramp/ffmpeg/FFprobe.java
Adds support for #93 
Also, I had to change the base java version to 11 due to this error:
```
[ERROR] Failed to execute goal com.spotify.fmt:fmt-maven-plugin:2.18:format (default) on project ffmpeg: Execution default of goal com.spotify.fmt:fmt-maven-plugin:2.18:format failed: An API incompatibility was encountered while executing com.spotify.fmt:fmt-maven-plugin:2.18:format: java.lang.UnsupportedClassVersionError: com/google/googlejavaformat/java/FormatterException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 54.0
```
> Allow extra arguments to FFprobe

- src/main/java/net/bramp/ffmpeg/info/Codec.java
- src/main/java/net/bramp/ffmpeg/probe/FFmpegStream.java
- src/main/java/net/bramp/ffmpeg/shared/CodecType.java
- src/test/java/net/bramp/ffmpeg/FFprobeTest.java
> Merge CodecType enums and add missing Attachment codec

- src/main/java/net/bramp/ffmpeg/probe/FFmpegChapter.java
- src/test/java/net/bramp/ffmpeg/FFprobeTest.java
- src/test/java/net/bramp/ffmpeg/fixtures/Samples.java
- src/test/resources/net/bramp/ffmpeg/fixtures/chapters_with_long_id.m4b
This closes #296.
The data provided in the issue is sadly not complete, but using an existing file and adding the chapter information I could re-create a minimal test to accompany the fix
> Change FFmpegChapter#id type to long

- pom.xml
> Replace animal-sniffer with javac parameter

- src/test/java/net/bramp/ffmpeg/FFprobeTest.java
This allows using the FFPROBE environment variable when running tests locally
> fix: Don't check if the ffprobe executable path matches while testing

- src/main/java/net/bramp/ffmpeg/FFcommon.java
- src/main/java/net/bramp/ffmpeg/FFmpegException.java
- src/main/java/net/bramp/ffmpeg/FFprobe.java
- src/test/java/net/bramp/ffmpeg/FFprobeTest.java
Similar idea to https://github.com/bramp/ffmpeg-cli-wrapper/pull/214 but for ffprobe. Ffprobe actually already deserialises the errors into FFmpegError (Error codes too!) in the FFmpegProbeResult. The result is never returned though as we discard everything and throw IOException.
This change throws FFmpegException which contains the FFmpegError and will allow consumers to easily handle things like 401/404 scenarios on remote files.
> Propagate FFmpegError through FFmpegException on FFprobe failures

- src/main/java/net/bramp/ffmpeg/FFmpegUtils.java
- src/main/java/net/bramp/ffmpeg/builder/FFmpegHlsOutputBuilder.java
- src/test/java/net/bramp/ffmpeg/builder/FFmpegHlsOutputBuilderTest.java
This reverts commit c932b7875d045572b8dbf27b41fb042ef7104677.
> Revert "Bug/347 invalid chars in hls time (#348)"
